version: '2.1'
services:

    dovecot-mailcow:
      ports:
        - '[2a00:dead:beef::abc]:143:143'
        - '[2a00:dead:beef::abc]:993:993'
        - '[2a00:dead:beef::abc]:110:110'
        - '[2a00:dead:beef::abc]:995:995'
        - '[2a00:dead:beef::abc]:4190:4190'

    postfix-mailcow:
      ports:
        - '[2a00:dead:beef::abc]:25:25'
        - '[2a00:dead:beef::abc]:465:465'
        - '[2a00:dead:beef::abc]:587:587'

    nginx-mailcow:
      ports:
        - '[2a00:dead:beef::abc]:80:80'
        - '[2a00:dead:beef::abc]:443:443'
